# a = {'班长':'fieldJBXXbz_Name', '辅导员':'fieldJBXXfdy_Name', '校内地址':'fieldJBXXxnjzbgdz'}

import time

def formdata_init(data:dict, clock_form_url, tags, instanceName, ymtime: int):
    formdata = {}

    formdata['fieldJKMsfwlm'] = '1' # 绿码
    formdata['fieldJKMjt'] = '' # 非绿码截图
    # now = int(time.time())
    # if 691200 > now-ymtime > 0:
    #     formdata['fieldYZNSFJCHS'] = "1" # 一周内是否进行了核酸检测
    #     formdata['fieldJCSJ'] = ymtime # 核酸检测时间
    # else:
    #     formdata['fieldYZNSFJCHS'] = "2"
    #     formdata['fieldJCSJ'] = ""

    formdata['fieldSFJZYM'] = data.get('fieldSFJZYM') # 是否接种疫苗
    if formdata['fieldSFJZYM'] == "1":
        formdata['fieldJZDZC'] = data.get('fieldJZDZC') # 接种针数

    formdata['_VAR_EXECUTE_INDEP_ORGANIZE_Name'] = data.get('_VAR_EXECUTE_INDEP_ORGANIZE_Name', '')
    formdata['_VAR_ACTION_INDEP_ORGANIZES_Codes'] = data.get('_VAR_ACTION_INDEP_ORGANIZES_Codes', '')
    formdata['_VAR_ACTION_REALNAME'] = data.get('_VAR_ACTION_REALNAME', '')
    formdata['_VAR_ACTION_ORGANIZE'] = data.get('_VAR_ACTION_ORGANIZE', '')
    formdata['_VAR_EXECUTE_ORGANIZE'] = data.get('_VAR_EXECUTE_ORGANIZE', '')
    formdata['_VAR_ACTION_INDEP_ORGANIZE'] = data.get('_VAR_ACTION_INDEP_ORGANIZE', '')
    formdata['_VAR_ACTION_INDEP_ORGANIZE_Name'] = data.get('_VAR_ACTION_INDEP_ORGANIZE_Name', '')
    formdata['_VAR_ACTION_ORGANIZE_Name'] = data.get('_VAR_ACTION_ORGANIZE_Name', '')
    formdata['_VAR_EXECUTE_ORGANIZES_Names'] = data.get('_VAR_EXECUTE_ORGANIZES_Names', '')
    formdata['_VAR_OWNER_ORGANIZES_Codes'] = data.get('_VAR_OWNER_ORGANIZES_Codes', '')
    formdata['_VAR_ADDR'] = data.get('_VAR_ADDR', '')
    formdata['_VAR_OWNER_ORGANIZES_Names'] = data.get('_VAR_OWNER_ORGANIZES_Names', '')
    formdata['_VAR_URL'] = clock_form_url
    formdata['_VAR_EXECUTE_ORGANIZE_Name'] = data.get('_VAR_EXECUTE_ORGANIZE_Name', '')
    formdata['_VAR_RELEASE'] = data.get('_VAR_RELEASE', '')
    formdata['_VAR_NOW_MONTH'] = data.get('_VAR_NOW_MONTH', '')
    formdata['_VAR_ACTION_USERCODES'] = data.get('_VAR_ACTION_USERCODES', '')
    formdata['_VAR_ACTION_ACCOUNT'] = data.get('_VAR_ACTION_ACCOUNT', '')
    formdata['_VAR_ACTION_INDEP_ORGANIZES_Names'] = data.get('_VAR_ACTION_INDEP_ORGANIZES_Names', '')
    formdata['_VAR_OWNER_ACCOUNT'] = data.get('_VAR_OWNER_ACCOUNT', '')
    formdata['_VAR_ACTION_ORGANIZES_Names'] = data.get('_VAR_ACTION_ORGANIZES_Names', '')
    formdata['_VAR_STEP_CODE'] = data.get('_VAR_STEP_CODE', '')
    formdata['_VAR_OWNER_USERCODES'] = data.get('_VAR_OWNER_USERCODES', '')
    formdata['_VAR_EXECUTE_ORGANIZES_Codes'] = data.get('_VAR_EXECUTE_ORGANIZES_Codes', '')
    formdata['_VAR_NOW_DAY'] = data.get('_VAR_NOW_DAY', '')
    formdata['_VAR_OWNER_REALNAME'] = data.get('_VAR_OWNER_REALNAME', '')
    formdata['_VAR_ENTRY_TAGS'] = tags
    formdata['_VAR_NOW'] = data.get('_VAR_NOW', '')
    formdata['_VAR_URL_Attr'] = data.get('_VAR_URL_Attr', '')
    formdata['_VAR_ENTRY_NUMBER'] = data.get('_VAR_ENTRY_NUMBER', '')
    formdata['_VAR_EXECUTE_INDEP_ORGANIZES_Names'] = data.get('_VAR_EXECUTE_INDEP_ORGANIZES_Names', '')
    formdata['_VAR_ENTRY_NAME'] = instanceName
    formdata['_VAR_STEP_NUMBER'] = data.get('_VAR_STEP_NUMBER', '')
    formdata['_VAR_POSITIONS'] = data.get('_VAR_POSITIONS', '')
    formdata['_VAR_EXECUTE_INDEP_ORGANIZES_Codes'] = data.get('_VAR_EXECUTE_INDEP_ORGANIZES_Codes', '')
    formdata['_VAR_EXECUTE_POSITIONS'] = data.get('_VAR_EXECUTE_POSITIONS', '')
    formdata['_VAR_ACTION_ORGANIZES_Codes'] = data.get('_VAR_ACTION_ORGANIZES_Codes', '')
    formdata['_VAR_EXECUTE_INDEP_ORGANIZE'] = data.get('_VAR_EXECUTE_INDEP_ORGANIZE', '')
    formdata['_VAR_NOW_YEAR'] = data.get('_VAR_NOW_YEAR', '')
    formdata['fieldFLid'] = data.get('fieldFLid', '')
    formdata['fieldHQRQ'] = data.get('fieldHQRQ', '')
    formdata['fieldDQSJ'] = int(data.get('fieldDQSJ', ''))
    formdata['fieldSQSJ'] = int(data.get('fieldSQSJ', ''))
    formdata['fieldJBXXxm'] = data.get('fieldJBXXxm', '')
    formdata['fieldJBXXxm_Name'] = data.get('fieldJBXXxm_Name', '')
    formdata['fieldJBXXgh'] = data.get('fieldJBXXgh', '')
    formdata['fieldJBXXnj'] = data.get('fieldJBXXnj', '')
    formdata['fieldJBXXbj'] = data.get('fieldJBXXbj', '')
    formdata['fieldJBXXxb'] = data.get('fieldJBXXxb', '')
    formdata['fieldJBXXxb_Name'] = data.get('fieldJBXXxb_Name', '')
    formdata['fieldJBXXlxfs'] = data.get('fieldJBXXlxfs', '')
    formdata['fieldJBXXcsny'] = data.get('fieldJBXXcsny', '')
    formdata['fieldJBXXdw'] = data.get('fieldJBXXdw', '')
    formdata['fieldJBXXdw_Name'] = data.get('fieldJBXXdw_Name', '')
    formdata['fieldJBXXbz'] = data.get('fieldJBXXbz', '')
    formdata['fieldJBXXbz_Name'] = data.get('fieldJBXXbz_Name', '')
    formdata['fieldJBXXbz_Attr'] = f'{{"_parent":"{data.get("fieldJBXXbj", "")}"}}'
    formdata['fieldJBXXfdy'] = data.get('fieldJBXXfdy', '')
    formdata['fieldJBXXfdy_Name'] = data.get('fieldJBXXfdy_Name', '')
    formdata['fieldJBXXfdy_Attr'] = f'{{"_parent":"{data.get("fieldJBXXdw", "")}:*"}}'
    formdata['fieldjgs'] = data.get('fieldjgs', '')
    formdata['fieldjgs_Name'] = data.get('fieldjgs_Name', '')
    formdata['fieldjgshi'] = data.get('fieldjgshi', '')
    formdata['fieldjgshi_Name'] = data.get('fieldjgshi_Name', '')
    formdata['fieldjgshi_Attr'] = f'{{"_parent":"{data.get("fieldjgs", "")}"}}'
    formdata['fieldJBXXxnjzbgdz'] = data.get('fieldJBXXxnjzbgdz', '')
    formdata['fieldJBXXJG'] = data.get('fieldJBXXJG', '')
    formdata['fieldJBXXjgs'] = data.get('fieldJBXXjgs', '')
    formdata['fieldJBXXjgs_Name'] = data.get('fieldJBXXjgs_Name', '')
    formdata['fieldJBXXjgshi'] = data.get('fieldJBXXjgshi', '')
    formdata['fieldJBXXjgshi_Name'] = data.get('fieldJBXXjgshi_Name', '')
    formdata['fieldJBXXjgshi_Attr'] = f'{{"_parent":"{data.get("fieldJBXXjgs", "")}"}}'
    formdata['fieldJBXXjgq'] = data.get('fieldJBXXjgq', '')
    formdata['fieldJBXXjgq_Name'] = data.get('fieldJBXXjgq_Name', '')
    formdata['fieldJBXXjgq_Attr'] = f'{{"_parent":"{data.get("fieldJBXXjgshi", "")}"}}'
    formdata['fieldJBXXjgsjtdz'] = data.get('fieldJBXXjgsjtdz', '')
    formdata['fieldJBXXdrsfwc'] = data.get('fieldJBXXdrsfwc', '')
    formdata['fieldJBXXsheng'] = data.get('fieldJBXXsheng', '')
    formdata['fieldJBXXsheng_Name'] = data.get('fieldJBXXsheng_Name', '')
    formdata['fieldJBXXshi'] = data.get('fieldJBXXshi', '')
    formdata['fieldJBXXshi_Name'] = data.get('fieldJBXXshi_Name', '')
    formdata['fieldJBXXshi_Attr'] =f'{{"_parent":""}}'
    formdata['fieldJBXXqu'] = data.get('fieldJBXXqu', '')
    formdata['fieldJBXXqu_Name'] = data.get('fieldJBXXqu_Name', '')
    formdata['fieldJBXXqu_Attr'] =f'{{"_parent":""}}'
    formdata['fieldJBXXqjtxxqk'] = data.get('fieldJBXXqjtxxqk', '')
    formdata['fieldSTQKbrstzk1'] = data.get('fieldSTQKbrstzk1', '')

    formdata['fieldSTQKfs'] = bool(data.get('fieldSTQKks', ''))
    formdata['fieldSTQKks'] = bool(data.get('fieldSTQKks', ''))
    formdata['fieldSTQKxm'] = bool(data.get('fieldSTQKxm', ''))
    formdata['fieldSTQKfl'] = bool(data.get('fieldSTQKfl', ''))
    formdata['fieldSTQKhxkn'] = bool(data.get('fieldSTQKhxkn', ''))
    formdata['fieldSTQKfx'] = bool(data.get('fieldSTQKfx', ''))
    formdata['fieldSTQKqt'] = bool(data.get('fieldSTQKqt', ''))
    formdata['fieldSTQKqtms'] = data.get('fieldSTQKqtms', '')
    formdata['fieldSTQKfrtw'] = data.get('fieldSTQKfrtw', '')
    formdata['fieldSTQKfrsj'] = data.get('fieldSTQKfrsj', '')
    formdata['fieldSTQKclfs'] = data.get('fieldSTQKclfs', '')
    formdata['fieldSTQKzd'] = data.get('fieldSTQKzd', '')
    formdata['fieldSTQKbrstzk'] = data.get('fieldSTQKbrstzk', '')
    formdata['fieldSTQKglfs'] = data.get('fieldSTQKglfs', '')
    formdata['fieldSTQKgldd'] = data.get('fieldSTQKgldd', '')
    formdata['fieldSTQKglkssj'] = data.get('fieldSTQKglkssj', '')
    formdata['fieldSTQKzdjgmc'] = data.get('fieldSTQKzdjgmc', '')
    formdata['fieldSTQKzdmc'] = data.get('fieldSTQKzdmc', '')
    formdata['fieldSTQKzdkssj'] = data.get('fieldSTQKzdkssj', '')
    formdata['fieldSTQKzljgmc'] = data.get('fieldSTQKzljgmc', '')
    formdata['fieldSTQKzysj'] = data.get('fieldSTQKzysj', '')
    formdata['fieldSTQKzdjgmcc'] = data.get('fieldSTQKzdjgmcc', '')
    formdata['fieldSTQKpcsj'] = data.get('fieldSTQKpcsj', '')
    formdata['fieldSTQKjtcystzk1'] = data.get('fieldSTQKjtcystzk1', '')
    formdata['fieldSTQKjtcyfs'] = bool(data.get('fieldSTQKjtcyfs', ''))
    formdata['fieldSTQKjtcyks'] = bool(data.get('fieldSTQKjtcyks', ''))
    formdata['fieldSTQKjtcyxm'] = bool(data.get('fieldSTQKjtcyxm', ''))
    formdata['fieldSTQKjtcyfl'] = bool(data.get('fieldSTQKjtcyfl', ''))
    formdata['fieldSTQKjtcyhxkn'] = bool(data.get('fieldSTQKjtcyhxkn', ''))
    formdata['fieldSTQKjtcyfx'] = bool(data.get('fieldSTQKjtcyfx', ''))
    formdata['fieldSTQKjtcyqt'] = bool(data.get('fieldSTQKjtcyqt', ''))
    formdata['fieldSTQKjtcyqtms'] = data.get('fieldSTQKjtcyqtms', '')
    formdata['fieldSTQKjtcyfrtw'] = data.get('fieldSTQKjtcyfrtw', '')
    formdata['fieldSTQKjtcyfrsj'] = data.get('fieldSTQKjtcyfrsj', '')
    formdata['fieldSTQKjtcyclfs'] = data.get('fieldSTQKjtcyclfs', '')
    formdata['fieldSTQKjtcyzd'] = data.get('fieldSTQKjtcyzd', '')
    formdata['fieldSTQKjtcystzk'] = data.get('fieldSTQKjtcystzk', '')
    formdata['fieldSTQKjtcyglfs'] = data.get('fieldSTQKjtcyglfs', '')
    formdata['fieldSTQKjtcygldd'] = data.get('fieldSTQKjtcygldd', '')

    formdata['fieldSTQKjtcyglkssj'] = data.get('fieldSTQKjtcyglkssj', '')
    formdata['fieldSTQKjtcyzdjgmc'] = data.get('fieldSTQKjtcyzdjgmc', '')
    formdata['fieldSTQKjtcyzdmc'] = data.get('fieldSTQKjtcyzdmc', '')
    formdata['fieldSTQKjtcyzdkssj'] = data.get('fieldSTQKjtcyzdkssj', '')
    formdata['fieldSTQKjtcyzljgmc'] = data.get('fieldSTQKjtcyzljgmc', '')
    formdata['fieldSTQKjtcyzysj'] = data.get('fieldSTQKjtcyzysj', '')
    formdata['fieldSTQKjtcyzdjgmcc'] = data.get('fieldSTQKjtcyzdjgmcc', '')
    formdata['fieldSTQKjtcypcsj'] = data.get('fieldSTQKjtcypcsj', '')
    formdata['fieldSTQKrytsqkqsm'] = data.get('fieldSTQKrytsqkqsm', '')
    formdata['fieldCXXXszsqsfyyshqzbl'] = data.get('fieldCXXXszsqsfyyshqzbl', '')
    formdata['fieldCXXXqjymsxgqk'] = data.get('fieldCXXXqjymsxgqk', '')
    formdata['fieldCXXXsfjcgyshqzbl'] = data.get('fieldCXXXsfjcgyshqzbl', '')

    formdata['fieldCXXXksjcsj'] = data.get('fieldCXXXksjcsj', '')
    formdata['fieldCXXXzhycjcsj'] = data.get('fieldCXXXzhycjcsj', '')
    formdata['fieldJCDDs'] = data.get('fieldJCDDs', '')
    formdata['fieldJCDDs_Name'] = data.get('fieldJCDDs_Name', '')
    formdata['fieldJCDDshi'] = data.get('fieldJCDDshi', '')
    formdata['fieldJCDDshi_Name'] = data.get('fieldJCDDshi_Name', '')
    formdata['fieldJCDDshi_Attr'] =f'{{"_parent":""}}'
    formdata['fieldJCDDq'] = data.get('fieldJCDDq', '')
    formdata['fieldJCDDq_Name'] = data.get('fieldJCDDq_Name', '')
    formdata['fieldJCDDq_Attr'] =f'{{"_parent":""}}'
    formdata['fieldJCDDqmsjtdd'] = data.get('fieldJCDDqmsjtdd', '')
    formdata['fieldCXXXjcdr'] = data.get('fieldCXXXjcdr', '')

    formdata['fieldCXXXjcdqk'] = data.get('fieldCXXXjcdqk', '')
    formdata['fieldYQJLsfjcqtbl'] = data.get('fieldYQJLsfjcqtbl', '')
    formdata['fieldYQJLksjcsj'] = data.get('fieldYQJLksjcsj', '')
    formdata['fieldYQJLzhycjcsj'] = data.get('fieldYQJLzhycjcsj', '')
    formdata['fieldYQJLjcdry'] = data.get('fieldYQJLjcdry', '')
    formdata['fieldYQJLjcdds'] = data.get('fieldYQJLjcdds', '')
    formdata['fieldYQJLjcdds_Name'] = data.get('fieldYQJLjcdds_Name', '')
    formdata['fieldYQJLjcddshi'] = data.get('fieldYQJLjcddshi', '')
    formdata['fieldYQJLjcddshi_Name'] = data.get('fieldYQJLjcddshi_Name', '')
    formdata['fieldYQJLjcddshi_Attr'] =f'{{"_parent":""}}'
    formdata['fieldYQJLjcddq'] = data.get('fieldYQJLjcddq', '')
    formdata['fieldYQJLjcddq_Name'] = data.get('fieldYQJLjcddq_Name', '')
    formdata['fieldYQJLjcddq_Attr'] =f'{{"_parent":""}}'

    formdata['fieldYQJLjcdryjkqk'] = data.get('fieldYQJLjcdryjkqk', '')
    formdata['fieldqjymsjtqk'] = data.get('fieldqjymsjtqk', '')
    formdata['fieldCXXXsftjhb'] = data.get('fieldCXXXsftjhb', '')
    formdata['fieldCXXXsftjhbjtdz'] = data.get('fieldCXXXsftjhbjtdz', '')
    formdata['fieldCXXXsftjhbjtdz_Name'] = data.get('fieldCXXXsftjhbjtdz_Name', '')
    formdata['fieldCXXXsftjhbs'] = data.get('fieldCXXXsftjhbs', '')
    formdata['fieldCXXXsftjhbs_Name'] = data.get('fieldCXXXsftjhbs_Name', '')
    formdata['fieldCXXXsftjhbs_Attr'] =f'{{"_parent":""}}'
    formdata['fieldCXXXsftjhbq'] = data.get('fieldCXXXsftjhbq', '')
    formdata['fieldCXXXsftjhbq_Name'] = data.get('fieldCXXXsftjhbq_Name', '')
    formdata['fieldCXXXsftjhbq_Attr'] =f'{{"_parent":""}}'
    formdata['fieldCXXXddsj'] = data.get('fieldCXXXddsj', '')
    formdata['fieldCXXXsfylk'] = data.get('fieldCXXXsfylk', '')

    formdata['fieldCXXXlksj'] = data.get('fieldCXXXlksj', '')
    formdata['fieldCNS'] = True
    formdata['fieldJKHDDzt'] = data.get('fieldJKHDDzt', '')
    formdata['fieldJKHDDzt_Name'] = data.get('fieldJKHDDzt_Name', '')
    formdata['fieldzgzjzdzq'] = data.get('fieldzgzjzdzq', '')
    formdata['fieldzgzjzdzq_Name'] = data.get('fieldzgzjzdzq_Name', '')
    formdata['fieldzgzjzdzq_Attr'] =f'{{"_parent":""}}'
    formdata['fieldzgzjzdzjtdz'] = data.get('fieldzgzjzdzjtdz', '')
    formdata['fieldzgzjzdzshi'] = data.get('fieldzgzjzdzshi', '')
    formdata['fieldzgzjzdzshi_Name'] = data.get('fieldzgzjzdzshi_Name', '')
    formdata['fieldzgzjzdzshi_Attr'] =f'{{"_parent":""}}'

    formdata['fieldzgzjzdzs'] = data.get('fieldzgzjzdzs', '')
    formdata['fieldzgzjzdzs_Name'] = data.get('fieldzgzjzdzs_Name', '')
    formdata['fieldCXXXcxzt'] = data.get('fieldCXXXcxzt', '')
    formdata['fieldCXXXjtgjbc'] = data.get('fieldCXXXjtgjbc', '')
    formdata['fieldCXXXjtfsqtms'] = data.get('fieldCXXXjtfsqtms', '')
    formdata['fieldCXXXjtfsqt'] = bool(data.get('fieldCXXXjtfsqt', ''))
    formdata['fieldCXXXjtfslc'] = bool(data.get('fieldCXXXjtfslc', ''))
    formdata['fieldCXXXjtfspc'] = bool(data.get('fieldCXXXjtfspc', ''))
    formdata['fieldCXXXjtfsdb'] = bool(data.get('fieldCXXXjtfsdb', ''))
    formdata['fieldCXXXjtfshc'] = bool(data.get('fieldCXXXjtfshc', ''))
    formdata['fieldCXXXjtfsfj'] = bool(data.get('fieldCXXXjtfsfj', ''))
    formdata['fieldCXXXfxcfsj'] = data.get('fieldCXXXfxcfsj', '')
    formdata['fieldCXXXcqwdq'] = data.get('fieldCXXXcqwdq', '')
    formdata['fieldCXXXdqszd'] = data.get('fieldCXXXdqszd', '')
    formdata['fieldCXXXssh'] = data.get('fieldCXXXssh', '')

    formdata['fieldCXXXfxxq'] = data.get('fieldCXXXfxxq', '')
    formdata['fieldCXXXfxxq_Name'] = data.get('fieldCXXXfxxq_Name', '')
    formdata['fieldCXXXjtjtzz'] = data.get('fieldCXXXjtjtzz', '')
    formdata['fieldCXXXjtzzq'] = data.get('fieldCXXXjtzzq', '')
    formdata['fieldCXXXjtzzq_Name'] = data.get('fieldCXXXjtzzq_Name', '')
    formdata['fieldCXXXjtzzs'] = data.get('fieldCXXXjtzzs', '')
    formdata['fieldCXXXjtzzs_Name'] = data.get('fieldCXXXjtzzs_Name', '')
    formdata['fieldCXXXjtzz'] = data.get('fieldCXXXjtzz', '')
    formdata['fieldCXXXjtzz_Name'] = data.get('fieldCXXXjtzz_Name', '')
    formdata['fieldSTQKqtqksm'] = data.get('fieldSTQKqtqksm', '')
    formdata['fieldSHENGYC'] = data.get('fieldSHENGYC', '')
    formdata['fieldYCFDY'] = data.get('fieldYCFDY', '')
    formdata['fieldYCBZ'] = data.get('fieldYCBZ', '')
    formdata['fieldYCBJ'] = data.get('fieldYCBJ', '')

    formdata['fieldLYYZM'] = data.get('fieldLYYZM', '')
    
    return formdata